version: '3.3'

services:
    portal:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: minimum/markdown-web
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: '3'
        ports:
          - '80:80'
        environment:
            FLASK_DEBUG: 0
        volumes:
          - type: bind
            source: ./flask/markdown
            target: /home/python/markdown
            read_only: true
